import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AdvancedNavbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <div className="bg-gray-900 lg:pt-4">
      <AdvancedNavbar />
        {children}
        <Footer />
        </div>
        </body>
    </html>
  );
}
